### ISSUE TITLE
protect against sim_prescale in predict model

### ISSUE THREAD

**Issue by RickKessler** [helenqu/scone#7]
While SIM_PRESCALE is sensible for training, it's a disaster for predict mode. Example: SIM_PRESCALE=20 means that only 5% of the events are classified while the remaining 95% are assigned Pia = PROB_SCONE=0. These PIa values result in crazy BBC output. To avoid wasting time again tracing such a mistake, please update scone to do one of the following when SIM_PRESCALE > 1 in predict mode:
1) abort with error message or
2) internally set SIM_PRESCALE=1 and continue

**Comment by helenqu** [comment]
fixed with https://github.com/dessn/Pippin/pull/152
